#!/bin/bash -eu
set -o pipefail

"${PIPELINE_SRC_ROOT}/db/druid/indexing/scripts/run_native_indexing.py" \
  --data_files='/home/share/data/brazil_covid/*/current/processed_rows.*' \
  --task_id_file="${PIPELINE_TMP_DIR}/task_id" \
  --datasource_name_file="${PIPELINE_TMP_DIR}/datasource_name" \
  --datasource_version_file="${PIPELINE_TMP_DIR}/datasource_version" \
  --min_data_date='1979-01-01' \
  --use_nested_json_format
