from models.python.config.pipeline_sources_settings import (
    PipelineSource,
    SharedPipelineStepType,
)

PIPELINE_CONFIG = [
    PipelineSource(
        source_id='confidence_interval',
        display_name='CI',
        extra_shared_steps=[SharedPipelineStepType.UPLOAD_PROCESSED_FILES],
    ),
    PipelineSource(
        source_id='corrections',
        display_name='CI Corrections',
        extra_shared_steps=[SharedPipelineStepType.RESAMPLE],
    ),
    PipelineSource(
        source_id='covid',
        display_name='COVID',
        extra_shared_steps=[SharedPipelineStepType.UPLOAD_PROCESSED_FILES],
    ),
    PipelineSource(
        source_id='gis',
        display_name='GIS',
        excluded_shared_steps=[
            SharedPipelineStepType.FILL_DIMENSION_DATA,
            SharedPipelineStepType.SYNC_DIGEST_FILES,
            SharedPipelineStepType.POPULATE_PIPELINE_RUN_METADATA,
        ],
    ),
    PipelineSource(
        source_id='mortality',
        display_name='Mortality',
        extra_shared_steps=[SharedPipelineStepType.UPLOAD_PROCESSED_FILES],
    ),
    PipelineSource(
        source_id='population',
        display_name='Population',
        extra_shared_steps=[
            SharedPipelineStepType.PATCH_LOCATIONS,
            SharedPipelineStepType.RESAMPLE,
            SharedPipelineStepType.UPLOAD_PROCESSED_FILES,
        ],
    ),
    PipelineSource(
        source_id='legacy_sim',
        display_name='Legacy SIM',
        extra_shared_steps=[
            SharedPipelineStepType.PATCH_LOCATIONS,
            SharedPipelineStepType.UPLOAD_PROCESSED_FILES,
        ],
    ),
    PipelineSource(source_id='self_serve', display_name='Self Serve'),
    PipelineSource(
        source_id='sim',
        display_name='SIM',
        extra_shared_steps=[SharedPipelineStepType.PATCH_LOCATIONS],
    ),
    PipelineSource(
        source_id='sinan',
        display_name='SINAN',
        extra_shared_steps=[
            SharedPipelineStepType.PATCH_LOCATIONS,
            SharedPipelineStepType.UPLOAD_PROCESSED_FILES,
        ],
    ),
    PipelineSource(
        source_id='sivep',
        display_name='SIVEP',
        extra_shared_steps=[
            SharedPipelineStepType.PATCH_LOCATIONS,
            SharedPipelineStepType.UPLOAD_PROCESSED_FILES,
        ],
    ),
]
