#!/bin/bash -eu
set -o pipefail

source "${PIPELINE_UTILS_DIR}/bash/common.sh"

pushd "${PIPELINE_FEED_DIR}" &> /dev/null

rm -rf "${PIPELINE_FEED_DIR}"/*

FetchFiles "gcs/zenysis-br/mortality/dataprep_output.csv.gz" .

popd &> /dev/null
