#!/bin/bash -eu
set -o pipefail

# NOTE(abby): Deactivating this step as this is historical data that doesn't get updated.
source "${PIPELINE_UTILS_DIR}/bash/common.sh"

SetupEnvForPyPy

pushd "${PIPELINE_FEED_DIR}" &> /dev/null

# Clean up old files from multiple runs.
rm -f *.csv.lz4

"${PIPELINE_BIN_DIR}/sim/fetch_sim_data.py" \
  --output_folder="${PIPELINE_FEED_DIR}" \
  --start_year=1979 \
  --end_year=2019

popd &> /dev/null
