DEMO_GROUPS = [
    {
        'groupId': 'sinan',
        'groupText': 'SINAN',
        'groupTextShort': 'SINAN',
        'hiddenByDefault': False,
        'indicators': [
            {
                'id': 'sinan_doenca_cardiovascular_cronica',
                'text': 'Doença Cardiovascular Crônica',
                'sub_area': 'Fatores de risco',
            },
            {
                'id': 'sinan_doenca_hematologica_cronica',
                'text': 'Doença Hematológica Crônica',
                'sub_area': 'Fatores de risco',
            },
            {
                'id': 'sinan_doenca_hepatica_cronica',
                'text': 'Doença Hepática Crônica',
                'sub_area': 'Fatores de risco',
            },
            {
                'id': 'sinan_doenca_neurologica_cronica',
                'text': 'Doença Neurológica Crónica',
                'sub_area': 'Fatores de risco',
            },
            {
                'id': 'sinan_doenca_renal_cronica',
                'text': 'Doença Renal Crônica',
                'sub_area': 'Fatores de risco',
            },
            {
                'id': 'sinan_imunodeficiencia_ou_imunodepressao',
                'text': 'Imunodeficiência ou Imunodepressão',
                'sub_area': 'Fatores de risco',
            },
            {
                'id': 'sinan_number_of_people_admitted_icu',
                'text': 'Pacientes Internados na UTI',
                'sub_area': 'Hospitalização',
            },
            {
                'id': 'sinan_number_of_people_hospitalized',
                'text': 'Pacientes Internados',
                'sub_area': 'Hospitalização',
            },
            {
                'id': 'sinan_number_of_people_hospitalized_cured',
                'text': 'Curado',
                'sub_area': 'Hospitalização',
            },
            {
                'id': 'sinan_number_of_people_hospitalized_died_in_investigation',
                'text': 'Óbito em investigação',
                'sub_area': 'Hospitalização',
            },
            {
                'id': 'sinan_number_of_people_hospitalized_died_of_infl',
                'text': 'Óbito por influenza',
                'sub_area': 'Hospitalização',
            },
            {
                'id': 'sinan_number_of_people_hospitalized_ignored',
                'text': 'Ignorado',
                'sub_area': 'Hospitalização',
            },
            {
                'id': 'sinan_number_of_people_hospitalized_other',
                'text': 'Óbito por outras causas',
                'sub_area': 'Hospitalização',
                'hide': True,
            },
            {
                'id': 'sinan_number_of_people_with_symptom_cough',
                'text': 'Pacientes com Tosse',
                'sub_area': 'Sinais e sintomas',
            },
            {
                'id': 'sinan_number_of_people_with_symptom_diffbreathing',
                'text': 'Pacientes com Desconforto Respiratorio',
                'sub_area': 'Sinais e sintomas',
            },
            {
                'id': 'sinan_number_of_people_with_symptom_dispneia',
                'text': 'Pacientes com Dispneia',
                'sub_area': 'Sinais e sintomas',
            },
            {
                'id': 'sinan_number_of_people_with_symptom_fever',
                'text': 'Pacientes com Febre',
                'sub_area': 'Sinais e sintomas',
            },
            {
                'id': 'sinan_number_of_people_with_symptom_soremuscles',
                'text': 'Pacientes com Mialgia',
                'sub_area': 'Sinais e sintomas',
            },
            {
                'id': 'sinan_number_of_people_with_symptom_sorethroat',
                'text': 'Pacientes com Dor de Garganta',
                'sub_area': 'Sinais e sintomas',
            },
            {
                'id': 'sinan_obesidade',
                'text': 'Obesidade',
                'sub_area': 'Fatores de risco',
            },
            {
                'id': 'sinan_outra_pneumatopatia_cronica',
                'text': 'Outra Pneumatopatia Crônica',
                'sub_area': 'Fatores de risco',
            },
            {'id': 'sinan_outros', 'text': 'Outros', 'sub_area': 'Fatores de risco'},
            {
                'id': 'sinan_puerpera',
                'text': 'Puérpera ',
                'sub_area': 'Fatores de risco',
            },
            {
                'id': 'sinan_sindrome_de_down',
                'text': 'Sindrome de down',
                'sub_area': 'Fatores de risco',
            },
            {
                'id': 'sinan_srag_por_agente_etiologico',
                'text': 'SRAG por não especificado',
                'sub_area': 'Classificação final do caso',
            },
            {
                'id': 'sinan_srag_por_influenza',
                'text': 'SRAG por influenza',
                'sub_area': 'Classificação final do caso',
            },
            {
                'id': 'sinan_srag_por_outro_agente_etiologico',
                'text': 'SRAG por outro agente etiologico',
                'sub_area': 'Classificação final do caso',
            },
            {
                'id': 'sinan_srag_por_outro_virus_respiratorio',
                'text': 'SRAG por outro virus respiratorio',
                'sub_area': 'Classificação final do caso',
            },
            {'id': 'sinan_total_number_of_cases_seen', 'text': 'Números de casos'},
            {
                'id': 'sinan_oportunidade_de_coleta_de_amostra_p_teste_diagnostico',
                'text': 'Oportunidade de coleta de amostra (p/ teste diagnóstico)',
                'sub_area': 'Indicadores de Oportunidade',
            },
            {
                'id': 'sinan_oportunidade_de_notificacao',
                'text': 'Oportunidade de notificação',
                'sub_area': 'Indicadores de Oportunidade',
            },
            {
                'id': 'sinan_tempo_de_internacao_internacao_e_o_desfecho',
                'text': 'Tempo de internação (internação e o desfecho)',
                'sub_area': 'Indicadores de Oportunidade',
            },
            {
                'id': 'sinan_tempo_de_internacao_na_uti_caso_va_a_obito_na_uti',
                'text': 'Tempo de internação na UTI (caso vá a óbito na UTI)',
                'sub_area': 'Indicadores de Oportunidade',
            },
            {
                'id': 'sinan_tempo_de_internacao_na_uti_entre_entrada_e_a_saida',
                'text': 'Tempo de internação na UTI (entre entrada e a saída)',
                'sub_area': 'Indicadores de Oportunidade',
            },
            # {
            #    'id': 'sinan_tempo_de_processamento_da_amostra_para_resultado_do_pcr',
            #    'text': 'Oportunidade de coleta de amostra (p/ teste diagnóstico)',
            # },
        ],
    },
    {
        'groupId': 'sivep',
        'groupText': 'SIVEP',
        'groupTextShort': 'SIVEP',
        'hiddenByDefault': False,
        'indicators': [
            {'id': 'sivep_asma', 'text': 'Asma', 'sub_area': 'Fatores de risco'},
            {
                'id': 'sivep_diabetes_mellitus',
                'text': 'Diabetes mellitus',
                'sub_area': 'Fatores de risco',
            },
            {
                'id': 'sivep_doenca_cardiovascular_cronica',
                'text': 'Doença Cardiovascular Crônica',
                'sub_area': 'Fatores de risco',
            },
            {
                'id': 'sivep_doenca_hematologica_cronica',
                'text': 'Doença Hematológica Crônica',
                'sub_area': 'Fatores de risco',
            },
            {
                'id': 'sivep_doenca_hepatica_cronica',
                'text': 'Doença Hepática Crônica',
                'sub_area': 'Fatores de risco',
            },
            {
                'id': 'sivep_doenca_neurologica_cronica',
                'text': 'Doença Neurológica Crónica',
                'sub_area': 'Fatores de risco',
            },
            {
                'id': 'sivep_doenca_renal_cronica',
                'text': 'Doença Renal Crônica',
                'sub_area': 'Fatores de risco',
            },
            {
                'id': 'sivep_imunodeficiencia_ou_imunodepressao',
                'text': 'Imunodeficiência ou Imunodepressão',
                'sub_area': 'Fatores de risco',
            },
            {
                'id': 'sivep_number_of_people_admitted_icu',
                'text': 'Pacientes Internados na UTI',
                'sub_area': 'Hospitalização',
            },
            {
                'id': 'sivep_number_of_people_hospitalized',
                'text': 'Casos de SRAG',
                'sub_area': 'Hospitalização',
            },
            {
                'id': 'sivep_number_of_people_hospitalized_cured',
                'text': 'Curado',
                'sub_area': 'Hospitalização',
            },
            {
                'id': 'sivep_number_of_people_hospitalized_died_in_investigation',
                'text': 'Óbito em investigação',
                'sub_area': 'Hospitalização',
                'hide': True,
            },
            {
                'id': 'sivep_number_of_people_hospitalized_died_of_infl',
                'text': 'Óbito por influenza',
                'sub_area': 'Hospitalização',
            },
            {
                'id': 'sivep_number_of_people_hospitalized_ignored',
                'text': 'Ignorado',
                'sub_area': 'Hospitalização',
            },
            {
                'id': 'sivep_number_of_people_hospitalized_other',
                'text': 'Óbito por outras causas',
                'sub_area': 'Hospitalização',
            },
            {
                'id': 'sivep_number_of_people_with_symptom_cough',
                'text': 'Pacientes com Tosse',
                'sub_area': 'Sinais e sintomas',
            },
            {
                'id': 'sivep_number_of_people_with_symptom_diffbreathing',
                'text': 'Pacientes com Desconforto Respiratorio',
                'sub_area': 'Sinais e sintomas',
            },
            {
                'id': 'sivep_number_of_people_with_symptom_dispneia',
                'text': 'Pacientes com Dispneia',
                'sub_area': 'Sinais e sintomas',
            },
            {
                'id': 'sivep_number_of_people_with_symptom_fever',
                'text': 'Pacientes com Febre',
                'sub_area': 'Sinais e sintomas',
            },
            {
                'id': 'sivep_number_of_people_with_symptom_sorethroat',
                'text': 'Pacientes com Dor de Garganta',
                'sub_area': 'Sinais e sintomas',
            },
            {
                'id': 'sivep_obesidade',
                'text': 'Obesidade',
                'sub_area': 'Fatores de risco',
            },
            {
                'id': 'sivep_outra_pneumatopatia_cronica',
                'text': 'Outra pneumatopatia cronica',
                'sub_area': 'Fatores de risco',
            },
            {'id': 'sivep_outros', 'text': 'Outros', 'sub_area': 'Fatores de risco'},
            {
                'id': 'sivep_puerpera',
                'text': 'Puérpera',
                'sub_area': 'Fatores de risco',
            },
            {
                'id': 'sivep_sindrome_de_down',
                'text': 'Sindrome de down',
                'sub_area': 'Fatores de risco',
            },
            {
                'id': 'sivep_srag_covid19',
                'text': 'COVID-19',
                'sub_area': 'Classificação final do caso',
            },
            {
                'id': 'sivep_srag_por_influenza',
                'text': 'SRAG por influenza',
                'sub_area': 'Classificação final do caso',
            },
            {
                'id': 'sivep_srag_por_nao_especificado',
                'text': 'SRAG não especificado',
                'sub_area': 'Classificação final do caso',
            },
            {
                'id': 'sivep_srag_por_outro_agente_etiologico',
                'text': 'SRAG por outro agente etiológico',
                'sub_area': 'Classificação final do caso',
            },
            {
                'id': 'sivep_srag_por_outro_virus_respiratorio',
                'text': 'SRAG por outro virus respiratório',
                'sub_area': 'Classificação final do caso',
            },
            {
                'id': 'sivep_srag_em_investigacao',
                'text': 'SRAG em investigação',
                'sub_area': 'Classificação final do caso',
            },
            {
                'id': 'sivep_srag_covid19_by_evaluation_date',
                'text': 'COVID-19 (Evolução)',
                'sub_area': 'Classificação final do caso',
            },
            {
                'id': 'sivep_srag_por_influenza_by_evaluation_date',
                'text': 'SRAG por influenza (Evolução)',
                'sub_area': 'Classificação final do caso',
            },
            {
                'id': 'sivep_srag_por_nao_especificado_by_evaluation_date',
                'text': 'SRAG não especificado (Evolução)',
                'sub_area': 'Classificação final do caso',
            },
            {
                'id': 'sivep_srag_por_outro_agente_etiologico_by_evaluation_date',
                'text': 'SRAG por outro agente etiológico (Evolução)',
                'sub_area': 'Classificação final do caso',
            },
            {
                'id': 'sivep_srag_por_outro_virus_respiratorio_by_evaluation_date',
                'text': 'SRAG por outro virus respiratório (Evolução)',
                'sub_area': 'Classificação final do caso',
            },
            {
                'id': 'sivep_srag_em_investigacao_by_evaluation_date',
                'text': 'SRAG em investigação (Evolução)',
                'sub_area': 'Classificação final do caso',
            },
            {
                'id': 'sivep_total_number_of_cases_seen',
                'text': 'Número de Notificações',
            },
            {
                'id': 'sivep_oportunidade_de_coleta_de_amostra_desde_a_notificacao',
                'text': 'Tempo em dias entre a identificação do caso (notificação) e a coleta da amostra para realização de teste diagnóstico',
                'sub_area': 'Indicadores de Oportunidade',
            },
            {
                'id': 'sivep_oportunidade_de_coleta_de_amostra_desde_inicio_dos_sintomas',
                'text': 'Tempo em dias entre o início dos sintomas e a coleta da amostra para realização de teste diagnóstico',
                'sub_area': 'Indicadores de Oportunidade',
            },
            {
                'id': 'sivep_tempo_de_internacao',
                'text': 'Tempo em dias entre o início da internação e a data do desfecho alta ou óbito',
                'sub_area': 'Indicadores de Oportunidade',
            },
            {
                'id': 'sivep_tempo_de_internacao_na_uti_entrada_e_a_saida',
                'text': 'Tempo em dias entre entrada e a saída da UTI',
                'sub_area': 'Indicadores de Oportunidade',
            },
            {
                'id': 'sivep_oportunidade_de_notificacao',
                'text': 'Tempo em dias entre o início dos sintomas e a notificação do caso',
                'sub_area': 'Indicadores de Oportunidade',
            },
            {
                'id': 'sivep_tempo_em_dias_entre_entrada_na_uti_e_o_desfecho_obito_caso_va_a_obito_na_uti',
                'text': 'Tempo em dias entre entrada na UTI e o desfecho óbito (caso vá a óbito na UTI)',
                'sub_area': 'Indicadores de Oportunidade',
            },
        ],
    },
    {
        'groupId': 'covid',
        'groupText': 'eSUS-VE',
        'groupTextShort': 'eSUS-VE',
        'hiddenByDefault': False,
        'indicators': [
            {
                'id': 'covid_teste_covid_19_positivo',
                'text': 'Teste COVID-19 Positivo',
                'sub_area': 'Resultado do Teste',
            },
            {
                'id': 'covid_covid19_teste_negativo',
                'text': 'Teste COVID-19 Negativo',
                'sub_area': 'Resultado do Teste',
            },
            {
                'id': 'covid_covid19_teste_noinfo',
                'text': 'Teste COVID-19 s/informação',
                'sub_area': 'Resultado do Teste',
            },
            {
                'id': 'covid_tests_collected_without_results',
                'text': 'Teste Coletado',
                'sub_area': 'Resultado do Teste',
            },
            {
                'id': 'covid_diabetes',
                'text': 'Diabetes',
                'sub_area': 'Fatores de risco',
            },
            {
                'id': 'covid_doencas_cardiacas_cronicas',
                'text': 'Doenças cardíacas crônicas',
                'sub_area': 'Fatores de risco',
            },
            {
                'id': 'covid_doencas_renais_cronicas_em_estagio_avancada',
                'text': 'Doenças renais crônicas em estágio avançado',
                'sub_area': 'Fatores de risco',
            },
            {
                'id': 'covid_doencas_respiratorias_cronicas_descompensadas',
                'text': 'Doenças respiratórias crônicas descompensadas',
                'sub_area': 'Fatores de risco',
            },
            {
                'id': 'covid_gestante_de_alto_risco',
                'text': 'Gestante de alto risco',
                'sub_area': 'Fatores de risco',
            },
            {
                'id': 'covid_imunossupressao',
                'text': 'Imunossupressão',
                'sub_area': 'Fatores de risco',
            },
            {
                'id': 'covid_number_of_people_canceled',
                'text': 'Cancelado',
                'sub_area': 'Hospitalização',
            },
            {
                'id': 'covid_number_of_people_home_care',
                'text': 'Em tratamento domiciliar',
                'sub_area': 'Hospitalização',
            },
            {
                'id': 'covid_number_of_people_hospitalized',
                'text': 'Pacientes Internados',
                'sub_area': 'Hospitalização',
            },
            {
                'id': 'covid_number_of_people_internado_em_uti',
                'text': 'Pacientes Internados em UTI',
                'sub_area': 'Hospitalização',
            },
            # {
            #    'id': 'covid_number_of_people_internado',
            #    'text': 'Internado',
            #    'sub_area': 'Hospitalização',
            # },
            {
                'id': 'covid_number_of_people_ignorado',
                'text': 'Ignorado',
                'sub_area': 'Hospitalização',
            },
            {
                'id': 'covid_number_of_people_hospitalized_cured',
                'text': 'Curado',
                'sub_area': 'Hospitalização',
            },
            {
                'id': 'covid_number_of_people_hospitalized_died_of_infl',
                'text': 'Óbito',
                'sub_area': 'Hospitalização',
                'hide': True,
            },
            {
                'id': 'covid_number_of_people_with_symptom_cough',
                'text': 'Tosse',
                'sub_area': 'Sinais e sintomas',
            },
            {
                'id': 'covid_number_of_people_with_symptom_diffbreathing',
                'text': 'Dificuldade de respirar',
                'sub_area': 'Sinais e sintomas',
            },
            {
                'id': 'covid_number_of_people_with_symptom_dispneia',
                'text': 'Dispneia',
                'sub_area': 'Sinais e sintomas',
            },
            {
                'id': 'covid_number_of_people_with_symptom_fever',
                'text': 'Febre',
                'sub_area': 'Sinais e sintomas',
            },
            {
                'id': 'covid_number_of_people_with_symptom_outros',
                'text': 'Outros',
                'sub_area': 'Sinais e sintomas',
            },
            {
                'id': 'covid_number_of_people_with_throat_fever',
                'text': 'Febredor_de_Garganta',
                'sub_area': 'Sinais e sintomas',
            },
            {
                'id': 'covid_number_of_people_with_symptom_sorethroat',
                'text': 'Dor de Garganta',
                'sub_area': 'Sinais e sintomas',
            },
            {
                'id': 'covid_portador_de_doencas_cromossomicas_ou_estado_de_fragilidade_imunologica',
                'text': 'Portador de doencas cromossomicas ou estado de fragilidade imunologica',
                'sub_area': 'Fatores de risco',
            },
            {
                'id': 'covid_total_cases_seen',
                'text': 'Números de casos suspeitos de COVID-19',
            },
            # {
            #'id': 'covid_oportunidade_de_encerramento_do_caso',
            #'text': '??',
            # },
            {
                'id': 'covid_oportunidade_de_notificacao',
                'text': 'Tempo em dias entre o início dos sintomas e a notificação do caso',
                'sub_area': 'Indicadores de Oportunidade',
            },
            {
                'id': 'covid_oportunidade_de_testagem',
                'text': 'Tempo em dias entre o início dos sintomas e a realização de teste diagnóstico',
                'sub_area': 'Indicadores de Oportunidade',
            },
        ],
    },
    {
        'groupId': 'mortality',
        'groupText': 'Registro Civil',
        'groupTextShort': 'Registro Civil',
        'hiddenByDefault': False,
        'indicators': [
            {
                'id': 'mortality_muni_covid',
                'text': 'Óbitos com suspeita ou confirmação de COVID-19',
                'sub_area': 'Município',
            },
            {
                'id': 'mortality_muni_indeterminate',
                'text': 'Óbitos indeterminados',
                'sub_area': 'Município',
            },
            {
                'id': 'mortality_muni_outras',
                'text': 'Demais óbitos',
                'sub_area': 'Município',
            },
            {
                'id': 'mortality_muni_pneumonia',
                'text': 'Óbitos por Pneumonia',
                'sub_area': 'Município',
            },
            {
                'id': 'mortality_muni_respiratory_insufficiency',
                'text': 'Óbitos por Insuficiência Respiratória',
                'sub_area': 'Município',
            },
            {
                'id': 'mortality_muni_sars',
                'text': 'Óbitos por SRAG',
                'sub_area': 'Município',
            },
            {
                'id': 'mortality_muni_septicemia',
                'text': 'Óbitos por Septicemia',
                'sub_area': 'Município',
            },
            {
                'id': 'mortality_state_covid',
                'text': 'Óbitos com suspeita ou confirmação de COVID-19',
                'sub_area': 'Estado',
            },
            {
                'id': 'mortality_state_indeterminate',
                'text': 'Óbitos indeterminados',
                'sub_area': 'Estado',
            },
            {
                'id': 'mortality_state_outras',
                'text': 'Demais óbitos',
                'sub_area': 'Estado',
            },
            {
                'id': 'mortality_state_pneumonia',
                'text': 'Óbitos por Pneumonia',
                'sub_area': 'Estado',
            },
            {
                'id': 'mortality_state_respiratory_insufficiency',
                'text': 'Óbitos por Insuficiência Respiratória',
                'sub_area': 'Estado',
            },
            {
                'id': 'mortality_state_sars',
                'text': 'Óbitos por SRAG',
                'sub_area': 'Estado',
            },
            {
                'id': 'mortality_state_septicemia',
                'text': 'Óbitos por Septicemia',
                'sub_area': 'Estado',
            },
        ],
    },
    {
        'groupId': 'confidence-interval',
        'groupText': 'Intervalos de Confiança',
        'groupTextShort': 'Intervalos de Confiança',
        'hiddenByDefault': False,
        'indicators': [
            {
                'id': 'confidence_municipality_f_0to59_lwr',
                'text': 'Feminino 0-59 5%',
                'sub_area': 'Capitais (UF)',
            },
            {
                'id': 'confidence_municipality_f_0to59_upr',
                'text': 'Feminino 0-59 95%',
                'sub_area': 'Capitais (UF)',
            },
            {
                'id': 'confidence_municipality_f_60_lwr',
                'text': 'Feminino 60+ 5%',
                'sub_area': 'Capitais (UF)',
            },
            {
                'id': 'confidence_municipality_f_60_upr',
                'text': 'Feminino 60+ 95%',
                'sub_area': 'Capitais (UF)',
            },
            {
                'id': 'confidence_municipality_f_lwr',
                'text': 'Feminino total 5%',
                'sub_area': 'Capitais (UF)',
            },
            {
                'id': 'confidence_municipality_f_upr',
                'text': 'Feminino total 95%',
                'sub_area': 'Capitais (UF)',
            },
            {
                'id': 'confidence_municipality_m_0to59_lwr',
                'text': 'Masculino 0-59 5%',
                'sub_area': 'Capitais (UF)',
            },
            {
                'id': 'confidence_municipality_m_0to59_upr',
                'text': 'Masculino 0-59 95%',
                'sub_area': 'Capitais (UF)',
            },
            {
                'id': 'confidence_municipality_m_60_lwr',
                'text': 'Masculino 60+ 5%',
                'sub_area': 'Capitais (UF)',
            },
            {
                'id': 'confidence_municipality_m_60_upr',
                'text': 'Masculino 60+ 95%',
                'sub_area': 'Capitais (UF)',
            },
            {
                'id': 'confidence_municipality_m_lwr',
                'text': 'Masculino total 5%',
                'sub_area': 'Capitais (UF)',
            },
            {
                'id': 'confidence_municipality_m_upr',
                'text': 'Masculino total 95%',
                'sub_area': 'Capitais (UF)',
            },
            {
                'id': 'confidence_municipality_total_0to59_lwr',
                'text': 'Total 0-59 5%',
                'sub_area': 'Capitais (UF)',
            },
            {
                'id': 'confidence_municipality_total_0to59_upr',
                'text': 'Total 0-59 95%',
                'sub_area': 'Capitais (UF)',
            },
            {
                'id': 'confidence_municipality_total_60_lwr',
                'text': 'Total 60+ 5%',
                'sub_area': 'Capitais (UF)',
            },
            {
                'id': 'confidence_municipality_total_60_upr',
                'text': 'Total 60+ 95%',
                'sub_area': 'Capitais (UF)',
            },
            {
                'id': 'confidence_municipality_total_lwr',
                'text': 'Total 5%',
                'sub_area': 'Capitais (UF)',
            },
            {
                'id': 'confidence_municipality_total_upr',
                'text': 'Total 95%',
                'sub_area': 'Capitais (UF)',
            },
            {
                'id': 'confidence_region_f_0to59_lwr',
                'text': 'Feminino 0-59 5%',
                'sub_area': 'Regiões',
            },
            {
                'id': 'confidence_region_f_0to59_upr',
                'text': 'Feminino 0-59 95%',
                'sub_area': 'Regiões',
            },
            {
                'id': 'confidence_region_f_60_lwr',
                'text': 'Feminino 60+ 5%',
                'sub_area': 'Regiões',
            },
            {
                'id': 'confidence_region_f_60_upr',
                'text': 'Feminino 60+ 95%',
                'sub_area': 'Regiões',
            },
            {
                'id': 'confidence_region_f_lwr',
                'text': 'Feminino total 5%',
                'sub_area': 'Regiões',
            },
            {
                'id': 'confidence_region_f_upr',
                'text': 'Feminino total 95%',
                'sub_area': 'Regiões',
            },
            {
                'id': 'confidence_region_m_0to59_lwr',
                'text': 'Masculino 0-59 5%',
                'sub_area': 'Regiões',
            },
            {
                'id': 'confidence_region_m_0to59_upr',
                'text': 'Masculino 0-59 95%',
                'sub_area': 'Regiões',
            },
            {
                'id': 'confidence_region_m_60_lwr',
                'text': 'Masculino 60+ 5%',
                'sub_area': 'Regiões',
            },
            {
                'id': 'confidence_region_m_60_upr',
                'text': 'Masculino 60+ 95%',
                'sub_area': 'Regiões',
            },
            {
                'id': 'confidence_region_m_lwr',
                'text': 'Masculino total 5%',
                'sub_area': 'Regiões',
            },
            {
                'id': 'confidence_region_m_upr',
                'text': 'Masculino total 95%',
                'sub_area': 'Regiões',
            },
            {
                'id': 'confidence_region_total_0to59_lwr',
                'text': 'Total 0-59 5%',
                'sub_area': 'Regiões',
            },
            {
                'id': 'confidence_region_total_0to59_upr',
                'text': 'Total 0-59 95%',
                'sub_area': 'Regiões',
            },
            {
                'id': 'confidence_region_total_60_lwr',
                'text': 'Total 60+ 5%',
                'sub_area': 'Regiões',
            },
            {
                'id': 'confidence_region_total_60_upr',
                'text': 'Total 60+ 95%',
                'sub_area': 'Regiões',
            },
            {
                'id': 'confidence_region_total_lwr',
                'text': 'Total 5%',
                'sub_area': 'Regiões',
            },
            {
                'id': 'confidence_region_total_upr',
                'text': 'Total 95%',
                'sub_area': 'Regiões',
            },
            {
                'id': 'confidence_state_f_0to59_lwr',
                'text': 'Feminino 0-59 5%',
                'sub_area': 'Estado',
            },
            {
                'id': 'confidence_state_f_0to59_upr',
                'text': 'Feminino 0-59 95%',
                'sub_area': 'Estado',
            },
            {
                'id': 'confidence_state_f_60_lwr',
                'text': 'Feminino 60+ 5%',
                'sub_area': 'Estado',
            },
            {
                'id': 'confidence_state_f_60_upr',
                'text': 'Feminino 60+ 95%',
                'sub_area': 'Estado',
            },
            {
                'id': 'confidence_state_f_lwr',
                'text': 'Feminino total 5%',
                'sub_area': 'Estado',
            },
            {
                'id': 'confidence_state_f_upr',
                'text': 'Feminino total 95%',
                'sub_area': 'Estado',
            },
            {
                'id': 'confidence_state_m_0to59_lwr',
                'text': 'Masculino 0-59 5%',
                'sub_area': 'Estado',
            },
            {
                'id': 'confidence_state_m_0to59_upr',
                'text': 'Masculino 0-59 95%',
                'sub_area': 'Estado',
            },
            {
                'id': 'confidence_state_m_60_lwr',
                'text': 'Masculino 60+ 5%',
                'sub_area': 'Estado',
            },
            {
                'id': 'confidence_state_m_60_upr',
                'text': 'Masculino 60+ 95%',
                'sub_area': 'Estado',
            },
            {
                'id': 'confidence_state_m_lwr',
                'text': 'Masculino total 5%',
                'sub_area': 'Estado',
            },
            {
                'id': 'confidence_state_m_upr',
                'text': 'Masculino total 95%',
                'sub_area': 'Estado',
            },
            {
                'id': 'confidence_state_total_0to59_lwr',
                'text': 'Total 0-59 5%',
                'sub_area': 'Estado',
            },
            {
                'id': 'confidence_state_total_0to59_upr',
                'text': 'Total 0-59 95%',
                'sub_area': 'Estado',
            },
            {
                'id': 'confidence_state_total_60_lwr',
                'text': 'Total 60+ 5%',
                'sub_area': 'Estado',
            },
            {
                'id': 'confidence_state_total_60_upr',
                'text': 'Total 60+ 95%',
                'sub_area': 'Estado',
            },
            {
                'id': 'confidence_state_total_lwr',
                'text': 'Total 5%',
                'sub_area': 'Estado',
            },
            {
                'id': 'confidence_state_total_upr',
                'text': 'Total 95%',
                'sub_area': 'Estado',
            },
            {
                'id': 'confidence_brazil_f_0to59_lwr',
                'text': 'Feminino 0-59 5%',
                'sub_area': 'Brazil',
            },
            {
                'id': 'confidence_brazil_f_0to59_upr',
                'text': 'Feminino 0-59 95%',
                'sub_area': 'Brazil',
            },
            {
                'id': 'confidence_brazil_f_60_lwr',
                'text': 'Feminino 60+ 5%',
                'sub_area': 'Brazil',
            },
            {
                'id': 'confidence_brazil_f_60_upr',
                'text': 'Feminino 60+ 95%',
                'sub_area': 'Brazil',
            },
            {
                'id': 'confidence_brazil_f_lwr',
                'text': 'Feminino Total 5%',
                'sub_area': 'Brazil',
            },
            {
                'id': 'confidence_brazil_f_upr',
                'text': 'Feminino Total 95%',
                'sub_area': 'Brazil',
            },
            {
                'id': 'confidence_brazil_m_0to59_lwr',
                'text': 'Male 0to59 5%',
                'sub_area': 'Brazil',
            },
            {
                'id': 'confidence_brazil_m_0to59_upr',
                'text': 'Masculino 0-59 95%',
                'sub_area': 'Brazil',
            },
            {
                'id': 'confidence_brazil_m_60_lwr',
                'text': 'Masculino 60+ 5%',
                'sub_area': 'Brazil',
            },
            {
                'id': 'confidence_brazil_m_60_upr',
                'text': 'Masculino 60+ 95%',
                'sub_area': 'Brazil',
            },
            {
                'id': 'confidence_brazil_m_lwr',
                'text': 'Masculino Total 5%',
                'sub_area': 'Brazil',
            },
            {
                'id': 'confidence_brazil_m_upr',
                'text': 'Masculino Total 95%',
                'sub_area': 'Brazil',
            },
            {
                'id': 'confidence_brazil_total_0to59_lwr',
                'text': 'Total 0-59 5%',
                'sub_area': 'Brazil',
            },
            {
                'id': 'confidence_brazil_total_0to59_upr',
                'text': 'Total 0-59 95%',
                'sub_area': 'Brazil',
            },
            {
                'id': 'confidence_brazil_total_60_lwr',
                'text': 'Total 60+ 5%',
                'sub_area': 'Brazil',
            },
            {
                'id': 'confidence_brazil_total_60_upr',
                'text': 'Total 60+ 95%',
                'sub_area': 'Brazil',
            },
            {
                'id': 'confidence_brazil_total_lwr',
                'text': 'Total 5%',
                'sub_area': 'Brazil',
            },
            {
                'id': 'confidence_brazil_total_upr',
                'text': 'Total 95%',
                'sub_area': 'Brazil',
            },
        ],
    },
    {
        'groupId': 'corrections',
        'groupText': 'Fatores de Correção (Registro Civil)',
        'groupTextShort': 'Fatores de Correção (Registro Civil)',
        'hiddenByDefault': False,
        'indicators': [
            {
                'id': 'corrections_brazil_correction_by_age_0_59',
                'text': 'Faixa Etária 0-59',
                'sub_area': 'Brazil',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_brazil_correction_by_age_60',
                'text': 'Faixa Etária 60+',
                'sub_area': 'Brazil',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_brazil_correction_by_female_60',
                'text': 'Sexo Feminino - Faixa Etária 60+',
                'sub_area': 'Brazil',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_brazil_correction_female',
                'text': 'Sexo Femino',
                'sub_area': 'Brazil',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_brazil_correction_female_0_59',
                'text': 'Sexo Feminino - Faixa Etária 0-59',
                'sub_area': 'Brazil',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_brazil_correction_male',
                'text': 'Sexo Masculino',
                'sub_area': 'Brazil',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_brazil_correction_male_0_59',
                'text': 'Sexo Masculino - Faixa Etária 0-59',
                'sub_area': 'Brazil',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_brazil_correction_male_60',
                'text': 'Sexo Masculino - Faixa Etária 60+',
                'sub_area': 'Brazil',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_brazil_corrections',
                'text': 'Fator de correção total',
                'sub_area': 'Brazil',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_region_level_correction_by_age_0_59',
                'text': 'Faixa Etária 0-59',
                'sub_area': 'Regiões',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_region_level_correction_by_age_60',
                'text': 'Faixa Etária 60+',
                'sub_area': 'Regiões',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_region_level_correction_by_female_60',
                'text': 'Sexo Feminino - Faixa Etária 60+',
                'sub_area': 'Regiões',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_region_level_correction_female',
                'text': 'Sexo Femino',
                'sub_area': 'Regiões',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_region_level_correction_female_0_59',
                'text': 'Sexo Feminino - Faixa Etária 0-59',
                'sub_area': 'Regiões',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_region_level_correction_male',
                'text': 'Sexo Masculino',
                'sub_area': 'Regiões',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_region_level_correction_male_0_59',
                'text': 'Sexo Masculino - Faixa Etária 0-59',
                'sub_area': 'Regiões',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_region_level_correction_male_60',
                'text': 'Sexo Masculino - Faixa Etária 60+',
                'sub_area': 'Regiões',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_region_level_corrections',
                'text': 'Fator de correção total',
                'sub_area': 'Regiões',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_state_level_correction_by_age_0_59',
                'text': 'Faixa Etária 0-59',
                'sub_area': 'Estado',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_state_level_correction_by_age_60',
                'text': 'Faixa Etária 60+',
                'sub_area': 'Estado',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_state_level_correction_by_female_60',
                'text': 'Sexo Feminino - Faixa Etária 60+',
                'sub_area': 'Estado',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_state_level_correction_female',
                'text': 'Sexo Femino',
                'sub_area': 'Estado',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_state_level_correction_female_0_59',
                'text': 'Sexo Feminino - Faixa Etária 0-59',
                'sub_area': 'Estado',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_state_level_correction_male',
                'text': 'Sexo Masculino',
                'sub_area': 'Estado',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_state_level_correction_male_0_59',
                'text': 'Sexo Masculino - Faixa Etária 0-59',
                'sub_area': 'Estado',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_state_level_correction_male_60',
                'text': 'Sexo Masculino - Faixa Etária 60+',
                'sub_area': 'Estado',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_state_level_corrections',
                'text': 'Fator de correção total',
                'sub_area': 'Estado',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_muni_level_correction_by_age_0_59',
                'text': 'Faixa Etária 0-59',
                'sub_area': 'Capitais (UF)',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_muni_level_correction_by_age_60',
                'text': 'Faixa Etária 60+',
                'sub_area': 'Capitais (UF)',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_muni_level_correction_by_female_60',
                'text': 'Sexo Feminino - Faixa Etária 60+',
                'sub_area': 'Capitais (UF)',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_muni_level_correction_female',
                'text': 'Sexo Femino',
                'sub_area': 'Capitais (UF)',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_muni_level_correction_female_0_59',
                'text': 'Sexo Feminino - Faixa Etária 0-59',
                'sub_area': 'Capitais (UF)',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_muni_level_correction_male',
                'text': 'Sexo Masculino',
                'sub_area': 'Capitais (UF)',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_muni_level_correction_male_0_59',
                'text': 'Sexo Masculino - Faixa Etária 0-59',
                'sub_area': 'Capitais (UF)',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_muni_level_correction_male_60',
                'text': 'Sexo Masculino - Faixa Etária 60+',
                'sub_area': 'Capitais (UF)',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
            {
                'id': 'corrections_muni_level_corrections',
                'text': 'Fator de correção total',
                'sub_area': 'Capitais (UF)',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
        ],
    },
    {
        'groupId': 'sim',
        'groupText': 'SIM',
        'groupTextShort': 'SIM',
        'hiddenByDefault': False,
        'indicators': [{'id': 'sim_obitos', 'text': 'Óbitos'}],
    },
    {
        'groupId': 'population',
        'groupText': 'População',
        'groupTextShort': 'População',
        'hiddenByDefault': False,
        'indicators': [
            {
                'id': 'population_population',
                'text': 'Population',
                'type': 'AVERAGE',
                'subtype': 'TIME_BUCKET',
            },
        ],
    },
]
