#!/bin/bash -eu
set -o pipefail

source "${PIPELINE_UTILS_DIR}/bash/common.sh"

pushd "${PIPELINE_FEED_DIR}" &> /dev/null

rm -rf "${PIPELINE_FEED_DIR}"/*

# FetchFiles "gcs/zenysis-br/COVID19/dataprep_output.csv.gz" .
curl https://zenysis-br-covid-assets.s3.amazonaws.com/raw_data/covid/dataprep_output.csv.gz > dataprep_output.csv.gz

popd &> /dev/null
