#!/bin/bash -eu
set -o pipefail

# Shard the input file so that we can parallelize the processing.

source "${PIPELINE_UTILS_DIR}/bash/common.sh"

SetupEnvForPyPy

# Remove any old files from previous pipeline runs.
rm -f "${PIPELINE_FEED_DIR}"/covid_data.*.csv.lz4

"${PIPELINE_SRC_ROOT}/scripts/shard_csv.py" \
  --input_file="${PIPELINE_FEED_DIR}/dataprep_output.csv.gz" \
  --output_file_pattern="${PIPELINE_FEED_DIR}/covid_data.#.csv.lz4" \
  --shard_size=5000000
