#!/bin/bash -eu
set -o pipefail

source "${PIPELINE_UTILS_DIR}/bash/common.sh"

SetupEnvForPyPy

"${PIPELINE_SRC_ROOT}/data/pipeline/scripts/process_csv.py" \
  --date 'date' \
  --enable_field_wildcards \
  --rename_cols \
    'dimension_hospitalizado:Hospitalization' \
  --multi_value_dimensions \
    'ComorbiditiesAndRiskFactors:dimension_puerpera,dimension_doenca_cardiovascular_cronica,dimension_doenca_hematologica_cronica,dimension_sindrome_de_down,dimension_doenca_hepatica_cronica,dimension_asma,dimension_diabetes_mellitus,dimension_doenca_neurologica_cronica,dimension_outra_pneumatopatia_cronica,dimension_imunodeficiencia,dimension_doenca_renal_cronica,dimension_obesidade,dimension_outros' \
  --prefix 'sivep' \
  --sourcename 'SIVEP' \
  --input="${PIPELINE_FEED_DIR}/sivep_converted.csv.lz4" \
  --output_locations="${PIPELINE_TMP_DIR}/locations_0.csv" \
  --output_fields="${PIPELINE_TMP_DIR}/fields_0.csv" \
  --output_rows="${PIPELINE_TMP_DIR}/processed_data_0.json.lz4"
