#!/bin/bash -eu
set -o pipefail

STEP='populate_pipeline_run_metadata'
SOURCES=($("${PIPELINE_SRC_ROOT}/data/pipeline/scripts/generate_pipeline_sources.py" ${STEP}))

# To run locally, add a --run_locally flag and replace the `source_out_dir`
# path to wherever the files are stored on your machine. Locally, this will
# commonly be something like:
# "${PIPELINE_SRC_ROOT}/pipeline/out/za/process/out/##SOURCE##/20210326" (replace
# the date '20210326' with the date in your pipeline out directory)
source_out_dir="/home/share/data/brazil_covid/##SOURCE##/current"

"${PIPELINE_SRC_ROOT}/data/pipeline/scripts/data_digest/populate_pipeline_run_metadata.py" \
  --sources "${SOURCES[@]}" \
  --source_out_dir "${source_out_dir}" \
  --metadata_digest_file 'metadata_digest_file.csv' \
  --mapped_locations_file 'mapped_locations.csv' \
  --unmatched_locations_file 'unmatched_locations.csv' \
  --deployment_names 'br-covid-web-staging' 'br-covid-web-prod'
