#!/bin/bash -eu
set -o pipefail

source "${PIPELINE_UTILS_DIR}/bash/common.sh"

SetupEnvForPyPy

MAPPINGS_DIR="${PIPELINE_BIN_DIR}/../static_data/mappings"

"${PIPELINE_SRC_ROOT}/data/pipeline/scripts/generate_metadata.py" \
  --canonical_mapping \
    "RegionName:${MAPPINGS_DIR}/region_mapped.csv" \
    "StateName:${MAPPINGS_DIR}/state_mapped.csv" \
    "HealthRegionName:${MAPPINGS_DIR}/health_region_mapped.csv" \
    "MunicipalityName:${MAPPINGS_DIR}/municipality_mapped.csv" \
  --output_metadata_map="${PIPELINE_OUT_DIR}/metadata_mapped.csv"
