#!/bin/bash -eu
set -o pipefail

source "${PIPELINE_UTILS_DIR}/bash/common.sh"

pushd "${PIPELINE_FEED_DIR}" &> /dev/null
latest_dir=$(GetLatestDirectory 's3/zenysis-br-covid/sim' 'cbo_codes.csv')

FetchFiles "${latest_dir}/cbo_codes.csv" .

popd &> /dev/null
