#!/bin/bash -eu
set -o pipefail

source "${PIPELINE_UTILS_DIR}/bash/common.sh"

pushd "${PIPELINE_FEED_DIR}" &> /dev/null
latest_dir_cid9=$(GetLatestDirectory 's3/zenysis-br-covid/sim' 'cid9.csv')
latest_dir_cid10=$(GetLatestDirectory 's3/zenysis-br-covid/sim' 'cid10_flat.csv')

FetchFiles "${latest_dir_cid9}/cid9.csv" .
FetchFiles "${latest_dir_cid10}/cid10_flat.csv" .

popd &> /dev/null
