#!/bin/bash -eu
set -o pipefail

source "${PIPELINE_UTILS_DIR}/bash/common.sh"


"${PIPELINE_BIN_DIR}/sim/convert_cid_csv.py" \
  --input_cid9="${PIPELINE_FEED_DIR}/cid9.csv" \
  --input_cid10="${PIPELINE_FEED_DIR}/cid10_flat.csv" \
  --cause_of_death_lookup="${PIPELINE_FEED_DIR}/output_cid.csv"
