#!/bin/bash -eu
set -o pipefail

# Clean up old files from multiple runs.
rm -f "${PIPELINE_TMP_DIR}"/sim_converted_*.csv.lz4

"${PIPELINE_BIN_DIR}/sim/convert_raw_sim.py" \
  --input_folder="${PIPELINE_FEED_DIR}" \
  --output_file_pattern="${PIPELINE_TMP_DIR}/sim_converted_#.csv.lz4" \
  --cause_of_death_codes_csv="${PIPELINE_FEED_DIR}/output_cid.csv"