#!/bin/bash -eu
set -o pipefail

"${PIPELINE_BIN_DIR}/sim/convert_raw_sim.py" \
  --input_folder="${PIPELINE_FEED_DIR}" \
  --output_file="${PIPELINE_FEED_DIR}/sim_converted.csv.lz4" \
  --cause_of_death_codes_csv="${PIPELINE_FEED_DIR}/output_cid.csv"