#!/bin/bash -eu
set -o pipefail

source "${PIPELINE_UTILS_DIR}/bash/common.sh"

SetupEnvForPyPy

"${PIPELINE_SRC_ROOT}/data/pipeline/scripts/process_csv.py" \
  --date 'date' \
  --enable_field_wildcards \
  --prefix 'sim_occurrence_' \
  --sourcename 'SIM' \
  --rename_cols \
    'RegionNameOcor:RegionName' \
    'StateNameOcor:StateName' \
    'HealthRegionNameOcor:HealthRegionName' \
    'MunicipalityNameOcor:MunicipalityName' \
  --input="${PIPELINE_FEED_DIR}/sim_converted.csv.lz4" \
  --output_locations="${PIPELINE_TMP_DIR}/locations_1.csv" \
  --output_fields="${PIPELINE_TMP_DIR}/fields_1.csv" \
  --output_rows="${PIPELINE_TMP_DIR}/processed_data_1.json.lz4"
