#!/bin/bash -eu
set -o pipefail

source "${PIPELINE_UTILS_DIR}/bash/common.sh"

SetupEnvForPyPy

"${PIPELINE_SRC_ROOT}/data/pipeline/scripts/process_csv.py" \
  --date 'date' \
  --enable_field_wildcards \
  --prefix 'sim_residence_' \
  --sourcename 'sim' \
  --rename_cols \
    'RegionNameRes:RegionName' \
    'StateNameRes:StateName' \
    'HealthRegionNameRes:HealthRegionName' \
    'MunicipalityNameRes:MunicipalityName' \
  --input="${PIPELINE_FEED_DIR}/sim_converted.csv.lz4" \
  --output_locations="${PIPELINE_TMP_DIR}/locations_0.csv" \
  --output_fields="${PIPELINE_TMP_DIR}/fields_0.csv" \
  --output_rows="${PIPELINE_TMP_DIR}/processed_data_0.json.lz4"
