#!/bin/bash -eu
set -o pipefail

# NOTE(abby): These steps consume a lot of RAM, use 12_ to ensure it doesn't run as
# other process steps are running.
source "${PIPELINE_UTILS_DIR}/bash/common.sh"

SetupEnvForPyPy

# Clean up old files from multiple runs.
rm -f "${PIPELINE_TMP_DIR}"/locations_ocor_*.csv
rm -f "${PIPELINE_TMP_DIR}"/fields_ocor_*.csv
rm -f "${PIPELINE_TMP_DIR}"/processed_data_ocor_*.json.lz4

# Track background process IDs so that we can reliably capture exit code
pids=()

count=0
for data_file in "${PIPELINE_TMP_DIR}"/sim_converted_*.csv.lz4 ; do
  # NOTE(abby): There are 30 cause of death dimensions that can all have multiple dimension
  # values. Causes A-D have component columns 0-3 and Causes 2 has component columns 0-5.
  "${PIPELINE_SRC_ROOT}/data/pipeline/scripts/process_csv.py" \
    --date 'date' \
    --enable_field_wildcards \
    --prefix 'sim_occurrence_' \
    --sourcename 'sim' \
    --rename_cols \
      'CODMUNOCOR:MunicipalityName' \
    --multi_value_dimensions \
      'CausesATitle:CausesATitle_0,CausesATitle_1,CausesATitle_2,CausesATitle_3' \
      'CausesAParent:CausesAParent_0,CausesAParent_1,CausesAParent_2,CausesAParent_3' \
      'CausesACategory1:CausesACategory1_0,CausesACategory1_1,CausesACategory1_2,CausesACategory1_3' \
      'CausesACategory2:CausesACategory2_0,CausesACategory2_1,CausesACategory2_2,CausesACategory2_3' \
      'CausesACategory3:CausesACategory3_0,CausesACategory3_1,CausesACategory3_2,CausesACategory3_3' \
      'CausesACategory4:CausesACategory4_0,CausesACategory4_1,CausesACategory4_2,CausesACategory4_3' \
      'CausesBTitle:CausesBTitle_0,CausesBTitle_1,CausesBTitle_2,CausesBTitle_3' \
      'CausesBParent:CausesBParent_0,CausesBParent_1,CausesBParent_2,CausesBParent_3' \
      'CausesBCategory1:CausesBCategory1_0,CausesBCategory1_1,CausesBCategory1_2,CausesBCategory1_3' \
      'CausesBCategory2:CausesBCategory2_0,CausesBCategory2_1,CausesBCategory2_2,CausesBCategory2_3' \
      'CausesBCategory3:CausesBCategory3_0,CausesBCategory3_1,CausesBCategory3_2,CausesBCategory3_3' \
      'CausesBCategory4:CausesBCategory4_0,CausesBCategory4_1,CausesBCategory4_2,CausesBCategory4_3' \
      'CausesCTitle:CausesCTitle_0,CausesCTitle_1,CausesCTitle_2,CausesCTitle_3' \
      'CausesCParent:CausesCParent_0,CausesCParent_1,CausesCParent_2,CausesCParent_3' \
      'CausesCCategory1:CausesCCategory1_0,CausesCCategory1_1,CausesCCategory1_2,CausesCCategory1_3' \
      'CausesCCategory2:CausesCCategory2_0,CausesCCategory2_1,CausesCCategory2_2,CausesCCategory2_3' \
      'CausesCCategory3:CausesCCategory3_0,CausesCCategory3_1,CausesCCategory3_2,CausesCCategory3_3' \
      'CausesCCategory4:CausesCCategory4_0,CausesCCategory4_1,CausesCCategory4_2,CausesCCategory4_3' \
      'CausesDTitle:CausesDTitle_0,CausesDTitle_1,CausesDTitle_2,CausesDTitle_3' \
      'CausesDParent:CausesDParent_0,CausesDParent_1,CausesDParent_2,CausesDParent_3' \
      'CausesDCategory1:CausesDCategory1_0,CausesDCategory1_1,CausesDCategory1_2,CausesDCategory1_3' \
      'CausesDCategory2:CausesDCategory2_0,CausesDCategory2_1,CausesDCategory2_2,CausesDCategory2_3' \
      'CausesDCategory3:CausesDCategory3_0,CausesDCategory3_1,CausesDCategory3_2,CausesDCategory3_3' \
      'CausesDCategory4:CausesDCategory4_0,CausesDCategory4_1,CausesDCategory4_2,CausesDCategory4_3' \
      'Causes2Title:Causes2Title_0,Causes2Title_1,Causes2Title_2,Causes2Title_3,Causes2Title_4,Causes2Title_5' \
      'Causes2Parent:Causes2Parent_0,Causes2Parent_1,Causes2Parent_2,Causes2Parent_3,Causes2Parent_4,Causes2Parent_5' \
      'Causes2Category1:Causes2Category1_0,Causes2Category1_1,Causes2Category1_2,Causes2Category1_3,Causes2Category1_4,Causes2Category1_5' \
      'Causes2Category2:Causes2Category2_0,Causes2Category2_1,Causes2Category2_2,Causes2Category2_3,Causes2Category2_4,Causes2Category2_5' \
      'Causes2Category3:Causes2Category3_0,Causes2Category3_1,Causes2Category3_2,Causes2Category3_3,Causes2Category3_4,Causes2Category3_5' \
      'Causes2Category4:Causes2Category4_0,Causes2Category4_1,Causes2Category4_2,Causes2Category4_3,Causes2Category4_4,Causes2Category4_5' \
    --disable_rollup \
    --input="${data_file}" \
    --output_locations="${PIPELINE_TMP_DIR}/locations_ocor_${count}.csv" \
    --output_fields="${PIPELINE_TMP_DIR}/fields_ocor_${count}.csv" \
    --output_rows="${PIPELINE_TMP_DIR}/processed_data_ocor_${count}.json.lz4" \
  | TagLines "$(basename "${data_file}")" &
  pids+=("$!")

  count=$((count + 1))
done

# Wait on each background process individually so that non-zero exit codes
# will be raised
WaitMultipleThreads "${pids[@]}"
