#!/bin/bash -eu
set -o pipefail

source "${PIPELINE_UTILS_DIR}/bash/common.sh"

pushd "${PIPELINE_FEED_DIR}" &> /dev/null

rm -rf "${PIPELINE_FEED_DIR}"/*

FetchFiles "gcs/zenysis-br/SIM/dataprep_output.csv.gz" .

mv dataprep_output.csv.gz dataprep_output_orig.csv.gz

# HACK(stephen): Rewrite invalid municipality code mapping number that exists in
# the raw SIM data to point to the correct number. This is easier than updating
# the municipality code mapping step to handle it since that code doesn't expect
# any invalid codes.
gunzip -c dataprep_output_orig.csv.gz \
  | perl -pe 's:"431453"$:"431454":' \
  | lz4 -3 \
  > dataprep_output.csv.lz4

popd &> /dev/null
